# Generated by Django 5.0.2 on 2024-02-13 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название категории', max_length=32, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=2)], verbose_name='название')),
                ('slug', models.SlugField(help_text='Ссылка', max_length=32, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=2)], verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
    ]
